version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  visualiser:
    build:
      context: ./services/visualiser
    image: visualiser-service:dev
    ports:
      - '3006:3006'
    depends_on:
      - rabbitmq

networks:
  default:
    name: event-demo-net
